Driver Service
viktordiktor/MicroservicesTaxiAggregator pull request #2
Opened 2024-01-28 21:22 UTC by viktordiktor

Created the main CRUD endpoints (/api/driver; /api/car).
Created entities using migrations.
Utilized ModelMapperand Lombok.
Implemented pagination and sorting.
Handled exceptions using @RestControllerAdvice.
Performed validation.

2024-01-30 10:14 UTC, AbandonedScope requested changes

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/controllers/DriverController.java
> +    @PostMapping("/car/{id}")
Чьё здесь id?
Если водителя, то корректнее будет написать /{driverId}/car

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/dto/CarRequest.java
> +    @Pattern(regexp = "\\d{4}\\s{2}\\d", message = ErrorList.WRONG_NUMBER_FORMAT)
Выноси регулярные выражения в константы

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/dto/DriverRequest.java
Регулярки вынеси в константы

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/services/CarServiceImpl.java
> +
Лишняя пустая строка

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/services/CarServiceImpl.java
> +        return optionalCar.get();
лучше используй метод Optional orElseThrow

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/services/DriverServiceImpl.java
> +        return optionalDriver.get();
orElseThrow

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/utils/ErrorList.java
> +    public static final String WRONG_CARD_FORMAT = "Card should be a 16-digit number!";
Либо везде добавь пустые строки, либо везде убери

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/utils/ModelMapperUtil.java
> +@Component
Может Configuration?

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/utils/RestExceptionHandler.java
Обработчики, которые возвращают одинаковые статусы можно объединить

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/resources/db/changelog/v-1.0/01-create-drivers-table.sql
> +) engine=InnoDB;
Что-то у тебя тут форматирование поехало

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/resources/db/changelog/v-2.0/30-insert-data-drivers-table.sql
> +                                                        (3, 'FANAT_UBER', '+375123456789', '5578113332345653');
```suggestion
INSERT INTO drivers (id, username, phone, credit_card)
 VALUES (1, 'VODILA_S_CHIZOVKI', '+375292547788', '1234567812345678'),
        (2, 'TAXIST2001', '+375222222222', '111111111111111'),
        (3, 'FANAT_UBER', '+375123456789', '5578113332345653');
```

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/models/Driver.java
> +    @JsonManagedReference
Зачем?

2024-01-30 10:14 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/exceptions/WrongPageableParameterException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
Зачем?

2024-01-30 15:51 UTC, AbandonedScope requested changes

2024-01-30 15:51 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/controllers/DriverController.java
> +@RequestMapping("/api/driver")
В названиях эндпоинтов лучше использовать множественное число (driver -> drivers)

2024-01-30 15:51 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/models/Driver.java
> +    @JsonManagedReference
И всё же, для чего тебе здесь эта аннотация?
Ты используешь objectMapper с этим энтити?

2024-01-30 15:51 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/services/DriverServiceImpl.java
> +    public Page<DriverResponse> getAllDrivers(int pageNumber, int pageSize, String sortField) {
Не заметил в прошлый раз:
Не возвращай спринговский Page в контроллер - это класс уровня доступа к данным, неправильно будет прокидывать его аж до контроллерв
Создай свой дто (можешь generic) который и возвращай

2024-01-30 15:51 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/utils/RestExceptionHandler.java
> +    }
А чего эти в один не объединил?

2024-01-31 09:20 UTC, viktordiktor commented on driver-service/src/main/java/com/nikonenko/driverservice/utils/RestExceptionHandler.java
> +    }
Почему то побоялся хахахахахаха, щас исправим

2024-01-31 10:20 UTC, AbandonedScope approved these changes

2024-01-31 10:20 UTC, AbandonedScope commented on driver-service/src/main/java/com/nikonenko/driverservice/controllers/DriverController.java
> +@RequestMapping("/api/drivers")
Ещё можно добавить версионирование API(сорри, сразу не обратил внимания, что нет)

2024-01-31 10:29 UTC, merged