Payment Service
viktordiktor/MicroservicesTaxiAggregator pull request #3
Opened 2024-02-04 22:02 UTC by viktordiktor

Created the main CRUD endpoints (/api/v1/payments/general; /api/v1/payments/customer).
Stripe integrated
Created entities using migrations.
Utilized ModelMapperand Lombok.
Implemented pagination and sorting.
Handled exceptions using @RestControllerAdvice.
Liquibase migrations added
Performed validation.

2024-02-06 06:44 UTC, pij1989 requested changes

2024-02-06 06:44 UTC, pij1989 commented on payment-service/pom.xml
> +                <artifactId>liquibase-maven-plugin</artifactId>
Зачем ликвибэйз плагин?

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/controllers/PaymentCustomerController.java
> +    @ResponseStatus(HttpStatus.OK)
@ResponseStatus(HttpStatus.OK) -  статус OK используется по дефолту и можно явно не указывать

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/controllers/PaymentCustomerController.java
> +    @PostMapping("/return-charge/{chargeId}")
Лучше "/charge/{chargeId}/return"

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/controllers/PaymentCustomerController.java
> +    @ResponseStatus(HttpStatus.OK)
@ResponseStatus(HttpStatus.OK) - статус OK используется по дефолту и можно явно не указывать

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/controllers/PaymentCustomerController.java
> +    @ResponseStatus(HttpStatus.OK)
@ResponseStatus(HttpStatus.OK) - статус OK используется по дефолту и можно явно не указывать

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/controllers/PaymentGeneralController.java
> +    @ResponseStatus(HttpStatus.OK)
@ResponseStatus(HttpStatus.OK) - статус OK используется по дефолту и можно явно не указывать

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/controllers/PaymentGeneralController.java
> +    @ResponseStatus(HttpStatus.OK)
@ResponseStatus(HttpStatus.OK) - статус OK используется по дефолту и можно явно не указывать

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/controllers/PaymentGeneralController.java
> +    @ResponseStatus(HttpStatus.OK)
Здесь наверное нужно `@ResponseStatus(HttpStatus.CREATED)`

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentCustomerServiceImpl.java
имплементации сервисов вынеси в пакет impl

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentCustomerServiceImpl.java
> +        System.out.println(amount);
Либо убери, либо добавь логгер

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentCustomerServiceImpl.java
> +        System.out.println(customer.getBalance());
Либо убери, либо добавь логгер

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentCustomerServiceImpl.java
> +        System.out.println(customer.getBalance());
Все System.out.println - либо убрать, либо заменить на логгер. Проверь во всех сервисах

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentCustomerServiceImpl.java
> +    private Double calculatePrice(CustomerRideRequest customerRideRequest) {
Все что касается денег (цена и т.п.) лучше использовать BigDecimal вместо Double

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentCustomerServiceImpl.java
> +        switch (dayOfWeek) {
```suggestion
        return switch (dayOfWeek) {
            case FRIDAY -> 1.6;
            case SATURDAY -> 1.4;
            case SUNDAY -> 1.2;
            default -> 1;
        };
```

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentCustomerServiceImpl.java
> +        if (time.isAfter(LocalTime.of(7, 0)) && time.isBefore(LocalTime.of(10, 0))) {
можно else убрать
```suggestion
          if (time.isAfter(LocalTime.of(7, 0)) && time.isBefore(LocalTime.of(10, 0))) {
            return 1.4;
        }
        
        if (time.isAfter(LocalTime.of(10, 0)) && time.isBefore(LocalTime.of(16, 0))) {
            return 1.0;
        }
        
        if (time.isAfter(LocalTime.of(16, 0)) && time.isBefore(LocalTime.of(19, 0))) {
            return 1.5;
        }
        
        if (time.isAfter(LocalTime.of(19, 0)) && time.isBefore(LocalTime.of(22, 0))) {
            return 1.2;
        }
        
        return 1.3;
```

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentCustomerServiceImpl.java
> +    private static Double getTimeCoefficient(LocalDateTime localDateTime) {
Методы getDayCoefficient и getTimeCoefficient можно вынести в отдельный утилитный класс например PaymentCoefficientUtil в пакет util, коэффициенты можно сделать константами

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/PaymentGeneralService.java
> +    ChargeResponse charge(ChargeRequest chargeRequest);
добавь пробел после метода

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/StripeUtilityService.java
Удали этот интерфейс, StripeUtilityServiceImpl переименуй в StripeUtil и вынеси в пакет util

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/services/StripeUtilityServiceImpl.java
> +public class StripeUtilityServiceImpl implements StripeUtilityService {
Удали интерфейс StripeUtilityService, StripeUtilityServiceImpl переименуй в StripeUtil и вынеси в пакет util

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/utils/ModelMapperUtil.java
> +public class ModelMapperUtil {
Это конфигурация, переименуй в ModelMapperConfig и вынеси в пакет config

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/utils/RestExceptionHandler.java
> +@ControllerAdvice
`@RestControllerAdvice`

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/java/com/nikonenko/paymentservice/utils/ValidationList.java
Ты для эксепшенов в ErrorList тянешь сообщения из проперти файла, а для валидаций используешь сообщения в константах. Может стоит для эксепшенов тоже сделать просто константы

2024-02-06 06:44 UTC, pij1989 commented on payment-service/src/main/resources/liquibase.properties
Зачем тебе liquibase.properties и ликвибэйз мавен плагин, если ты используешь ликвибэйз через спринг?

2024-02-06 11:39 UTC, viktordiktor commented on payment-service/src/main/java/com/nikonenko/paymentservice/utils/ValidationList.java
Просто просили выносить Exceptions в properties для локализации. А валидацию в properties не вынесешь (**Attribute value must be constant**)

2024-02-07 06:09 UTC, pij1989 approved these changes

2024-02-07 07:34 UTC, merged